spring:
    datasource:
        password: 
        url: jdbc:mysql://localhost:3307/iod2
        username: root#server:
#  ssl:
#    key-store: classpath:springboot.jks
#    key-store-password: password
#    key-store-type: jks
#    key-alias: springboot
#    key-password: password
#  port: 8443